name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install
      - name: Check Style
        run: |
          npm run eslint
      - name: Build
        run: |
          npm run build
      - name: Test
        run: |
          npm test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start server
        run: npm run start-prod &
      
      - name: Wait for server
        run: npx wait-on http://localhost:5000

      - name: Run Playwright tests
        run: npm run test:e2e
        
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: simple_deployment_pipeline
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Discord Webhook Notify Success
        if: success()
        uses: rjstone/discord-webhook-notify@v2.2.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: 'Deployment successful! 🚀'
          description: 'New version deployed to production'
          details: 'Commit: ${{ github.sha }}\nAuthor: ${{ github.actor }}\nBranch: ${{ github.ref_name }}'
      - name: Discord Webhook Notify Failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v2.2.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: 'Deployment failed! ❌'
          description: 'Deployment to production failed'
          details: 'Commit: ${{ github.sha }}\nAuthor: ${{ github.actor }}\nBranch: ${{ github.ref_name }}\nWorkflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
